version: "3"
services:
  p4d_svc:
    container_name: perforce-server
    build:
      context: .
      dockerfile: Dockerfile
    image: docker-perforce
    ports:
      - 1666:1666
    environment:
      - P4JOURNAL=/var/log/perforce/journal
      - P4LOG=/var/log/perforce/p4err
      - P4ROOT=/perforce_depot
      - P4PORT=localhost:1666
    command: /docker-perforce/p4dservice start
